spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workbook
    username: root
    password: 16581658
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        logging:
          level:
            org:
              hibernate:
                SQL=DEBUG:
                type:
                  descriptor:
                    sql:
                      BasicBinder=TRACE
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  security-scheme:
    name: Authorization
    type: http
    scheme: bearer